# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adfreereview', '0002_blog_post_profile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='domain_list',
            field=models.CharField(default='naver,daum,egloos,tistory', max_length=64),
        ),
    ]
